# Generated by Django 3.1.7 on 2021-03-25 04:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
